### ISSUE TITLE
Avoid publishing redundant packages to CI feed

### ISSUE THREAD

**Issue by atifaziz** [morelinq/MoreLINQ#681]
Today, every push to master also publishes a NuGet package to the [CI feed on MyGet](https://www.myget.org/F/morelinq/api/v3/index.json):

```yml
deploy:
- provider: NuGet
  server: https://www.myget.org/F/morelinq/api/v2/package
  api_key:
  symbol_server: https://www.myget.org/F/morelinq/symbols/api/v2/package
  on:
    branch: master
```

However, not each push changes the compiled binaries and so it's wasteful to publish redundant packages. We should use [C#'s deterministic building](https://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html
) ([`-deterministic`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/deterministic-compiler-option)) to avoid them. This would mean (I think) comparing [MVID](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.module.moduleversionid) of the new binaries against those of the binaries from last published package and upload the new package from CI/CD pipeline if there's any difference.

**Comment by atifaziz** [comment]
Looks like this needs to start with adding the following properties to `MoreLinq.csproj`:

```xml
<Deterministic>true</Deterministic>
<PathMap>$(MSBuildProjectDirectory)=.\</PathMap>
```

**Comment by atifaziz** [comment]
PowerShell can be used to query MVID:

    pwsh -C "Add-Type -Path MoreLinq.dll; [string][MoreLinq.MoreEnumerable].Assembly.Modules[0].ModuleVersionId"

**Comment by moh-hassan** [comment]
@atifaziz 
You can limit the generation of the package per tag only by adding `APPVEYOR_REPO_TAG` condition
When you push a tag to Appveyor, package will be pushed to MyGet.
The Package will be generated on artifact of appveyor and can be download manually from there (if needed).

```
deploy:
- provider: NuGet
  server: https://www.myget.org/F/morelinq/api/v2/package
  api_key:
  symbol_server: https://www.myget.org/F/morelinq/symbols/api/v2/package
  on:
    branch: master
  on:
    APPVEYOR_REPO_TAG: true    # add this line
```
